// 4 fal turu icin SEO landing icerik datasi.

export const fortunes = [
  {
    slug: 'kahve-fali',
    name: 'Kahve Fali',
    symbol: '☕',
    searchKeyword: 'kahve fali, kahve fali bak, online kahve fali, kahve telvesi yorumu, ucretsiz kahve fali',
    feature: 'coffee',
    intro: 'Kahve fali, Turk kahvesinin ardindan fincanin telvesinde olusan sekillerin yorumlanmasiyla yapilan, yuzyillara uzanan geleneksel bir fal turudur. Astro Dozi, bu kulturel mirasi yapay zeka destekli bilgisayar gorusu ile bulusturarak, fincanindaki sembolleri anlamli yorumlara donusturur.',
    history: 'Kahve falinin Osmanli sarayina kadar uzanan koklu bir gecmisi vardir. 16. yuzyilda kahvenin Anadolu\'ya gelmesiyle birlikte, telve okuma sanati da kadinlar arasinda hizla yayilmistir. Her bir sekil, kus, harf veya yol icin gelistirilmis sembol sozlugu, kusaktan kusaga aktarilmistir. Bugun de Turkiye\'de en sevilen fal turlerinden biri olarak yasamaktadir.',
    howTo: [
      'Turk kahvesini icmeden once niyet et, sevdiklerini dusun',
      'Kahveyi bitirdikten sonra fincanin agzini kapatip ters cevir',
      'Telvenin oturmasi icin yaklasik 5-10 dakika bekle',
      'Fincanin icindeki sekiller belirginlestiginde 4 farkli acidan fotograf cek',
      'Yapay zeka her sembolu analiz edip kisisel yorumunu hazirlasin',
    ],
    method: 'Astro Dozi\'nin kahve fali ozelligi, Google Gemini\'nin coklu modaliteli (multimodal) gorus modeli kullanir. Yukledigin 4 fincan fotografini analiz ederken, telvedeki spesifik sekilleri (kus, harf, yol benzeri cizgiler, kume) tanir ve geleneksel Turk sembol sozlugundeki anlamlariyla eslestirir. Sonuc, dogum haritana ve burcuna gore kisisellestirilir. Bu, App Store\'da rakipsiz bir ozelliktir: hicbir astroloji uygulamasi gercek bir nesneyi (kahve fincani) bilgisayar gorusu ile analiz etmiyor.',
    symbols: [
      { name: 'Kus', meaning: 'Iyi haber, mujde, beklenmeyen bir sevinc' },
      { name: 'Yol', meaning: 'Yeni baslangic, seyahat, kariyer degisikligi' },
      { name: 'Kalp', meaning: 'Ask, romantik bir gelisme, iliski derinlesmesi' },
      { name: 'Para', meaning: 'Beklenen veya ani gelir, finansal firsat' },
      { name: 'Yuzuk', meaning: 'Evlilik, soz, kalici bir baglilik' },
      { name: 'Balik', meaning: 'Bolluk, bereket, soyutla beklenenden cok kazanc' },
    ],
    cta: 'Fincanin fotografini cek, Astro Dozi\'nin AI yorumcusu birkac saniyede telveni okuyabilsin.',
  },
  {
    slug: 'tarot-fali',
    name: 'Tarot Fali',
    symbol: '🃏',
    searchKeyword: 'tarot fali, tarot kart fali, online tarot, ucretsiz tarot, tarot okumasi, tarot kart anlamlari',
    feature: 'tarot',
    intro: 'Tarot fali, 78 kartlik bir desteden cekilen kartlarin sembolizmi araciligiyla gecmis, simdiki an ve gelecek hakkinda icgoru sunan bir sezgi pratigidir. Astro Dozi, klasik Rider-Waite-Smith (RWS) destesini AI yorumlama gucuyle birlestirerek, her cekime kisisel anlam katar.',
    history: 'Tarot, 15. yuzyilda Italya\'da iskambil oyunu olarak baslayip, 18. yuzyilda mistik amacli kullanima evrilmistir. Bugun dunyanin en yaygin fal sistemlerinden biridir. 22 Buyuk Arkana karti, hayatin temel arketiplerini (Deli, Buyucu, Imparatorice, Asik); 56 Kucuk Arkana ise gunluk yasamin detaylarini temsil eder.',
    howTo: [
      'Niyetini netlestir: ask, kariyer veya genel rehberlik',
      'Aklindan sorunu sor, kalbini ac',
      'Kartlari karistir ve sezginle uc kart sec: gecmis, simdi, gelecek',
      'Her kart hem dik hem ters anlam tasir',
      'AI, secimini ve baglamini birlestirip kisisel yorum hazirlasin',
    ],
    method: 'Astro Dozi tam 78 kartlik RWS destesi sunar. Klasik 3-kartlik dilim (gecmis-simdi-gelecek), Celtic Cross veya tek kart cekimi yapabilirsin. Her kart icin Gemini AI, kartin sembolizmini senin dogum haritan, mevcut burcun ve sorunun ile birlestirir. Statik tarot uygulamalarinin aksine, ayni kart cekildiginde bile yorum her seferde farklidir.',
    symbols: [
      { name: 'Deli (0)', meaning: 'Yeni bir baslangic, cesur adim, sinirsiz potansiyel' },
      { name: 'Asik (VI)', meaning: 'Ask iliskisi, secim, bir hayati ortakliga adim' },
      { name: 'Carh (X)', meaning: 'Donguselerin degisimi, sans, kader donusu' },
      { name: 'Yildiz (XVII)', meaning: 'Umut, yenilenme, ruhsal rehberlik' },
      { name: 'Ay (XVIII)', meaning: 'Iluzyon, sezgi, gizemli icgoruler' },
      { name: 'Dunya (XXI)', meaning: 'Tamamlanma, basari, dongunun sonu' },
    ],
    cta: 'Bir niyet edip 3 kart cek; AI senin tarotunu okusun.',
  },
  {
    slug: 'ruya-yorumu',
    name: 'Ruya Yorumu',
    symbol: '💤',
    searchKeyword: 'ruya yorumu, ruya tabiri, ruyada gormek, ruya tabirleri online, ruya analizi ucretsiz',
    feature: 'dream',
    intro: 'Ruya yorumu (ruya tabiri), gece gordugun sembollerin bilincalti mesajlarini cozme sanatidir. Astro Dozi, gordugun ruyanin metnini analiz edip semboleri sozluklestirir, duygusal arka plani okur ve hayatindaki olas\'i karsiligini sunar.',
    history: 'Ruya yorumu hem dini hem psikolojik bir gelenektir. Antik Misir\'da Ruya Kitabi (Chester Beatty III) ile baslayan, Ibn Sirin\'in Islami yorumlarinda gelisen, Freud ve Jung\'la modern psikolojiye giren bu pratik, sembolun bilincaltindaki kok anlamini bulmayi amaclar.',
    howTo: [
      'Uyanir uyanmaz ruyanin notunu al; detay caycabuk silinir',
      'Ruyanin temel ogelerini yaz: kim, ne, nerede, his',
      'Ruyandaki dominant duyguyu (mutlu, korkulu, tuhaf) sec',
      'AI, sembolleri ayikleyip kisisel baglamla birlestirsin',
      'Onerilen anlam ile gercek hayatindaki situation karsilastir',
    ],
    method: 'Astro Dozi\'nin ruya tabiri ozelligi, Gemini AI ile ruya metnindeki sembolleri Ibn Sirin gelenegi, Jung arketipleri ve modern psikolojinin kesisiminde yorumlar. Ruya gunlugu (dream journal) tutarsan, AI haftalik desenleri analiz eder: hangi semboller tekrar ediyor, hangi duygu hakim, hangi konu islenmemis bir endise.',
    symbols: [
      { name: 'Su', meaning: 'Duygusal durum, bilincalti, arinma ya da bogulma' },
      { name: 'Ucmak', meaning: 'Ozgurluk arzusu, kontrol kaybi, hayallere acilim' },
      { name: 'Dis dokulmesi', meaning: 'Donusum kaygisi, kontrol kaybi, yeni evreye gecis' },
      { name: 'Yilan', meaning: 'Donusum, tehdit, sifa gucu, gizli bilgi' },
      { name: 'Ev', meaning: 'Kendi benligin, ruhsal alanin, kimliginin durumu' },
      { name: 'Bebek', meaning: 'Yeni proje, baslangic, korunmasi gereken bir nitelik' },
    ],
    cta: 'Bu gece gordugun ruyani yaz, AI haftalik analizini hazirlasin.',
  },
  {
    slug: 'avuc-ici-fali',
    name: 'Avuc Ici Fali',
    symbol: '✋',
    searchKeyword: 'avuc ici fali, el fali, palmistry, online el fali, el cizgilerinden fal',
    feature: 'palm',
    intro: 'Avuc ici fali (el fali, palmistry), elindeki cizgilerin bicim ve uzunluklarindan kisilik ve yasamla ilgili icgoru cikarma sanatidir. Astro Dozi, elinin fotografini analiz eden AI gorusu ile bu eski sanata digital bir derinlik katar.',
    history: 'El fali, 4000 yil onceye Hindistan\'a uzanan Veda gelenegi ile baslar. Antik Yunan\'da Aristoteles tarafindan incelendi, Cin\'de geleneksel tip ile birleti. Bati\'da 19. yuzyilda chiromancy adiyla bilim olarak da degerlendirildi. Elin uc ana cizgisi (kalp, hayat, kafa) ve aktif el (genelde yazi yazdigin) merkezi onem tasir.',
    howTo: [
      'Aktif elini (genelde yazi yazdigin el) sec',
      'Avuc icini iyi aydinlatilmis bir alana cevir',
      'Cizgilerin net gorunmesi icin elini hafifce ger',
      'Avucunun fotografini tum cizgiler gorunecek sekilde cek',
      'AI, kalp-hayat-kader cizgilerini ayri ayri yorumlasin',
    ],
    method: 'Astro Dozi\'nin avuc ici analizi, Gemini\'nin gorus modeli ile elinin fotografindaki ana cizgileri (kalp, hayat, kafa, kader) tespit eder. Her cizginin uzunlugu, derinligi ve baslangic noktasi geleneksel chiromancy verisiyle eslestirilir. Sonuc, dogum haritana gore kisisellestirilir. Telve okumasi gibi, bu da App Store\'da olmayan bilgisayar gorusu bazli bir ozelliktir.',
    symbols: [
      { name: 'Hayat Cizgisi', meaning: 'Yasam enerjisi, saglik, hayatindaki buyuk degisimler' },
      { name: 'Kalp Cizgisi', meaning: 'Romantik iliskiler, duygusal derinlik, ask hayati' },
      { name: 'Kafa Cizgisi', meaning: 'Zihinsel yetenek, karar verme tarzi, dusunce yapisi' },
      { name: 'Kader Cizgisi', meaning: 'Kariyer, basari, dis dunyanin etkisi' },
      { name: 'Gunes Cizgisi', meaning: 'Sanatsal yetenek, taninma, basariya giden yol' },
      { name: 'Evlilik Cizgisi', meaning: 'Onemli iliskiler, evlilik veya derin baglar' },
    ],
    cta: 'Avuc icinin fotografini cek, AI cizgilerini analiz etsin.',
  },
];
