// 4 fortune types in English for SEO landing content (premium copy)

export const fortunesEn = [
  {
    slug: 'coffee-reading',
    name: 'Coffee Reading',
    symbol: '☕',
    sceneKind: 'coffee',
    accent: '#C97A40',
    searchKeyword: 'coffee reading, coffee cup reading, online coffee fortune, coffee grounds interpretation, free coffee reading',
    feature: 'coffee',
    tagline: 'From Grounds, AI Insight',
    intro: 'Coffee reading is an ancient practice of interpreting shapes formed in Turkish coffee grounds after drinking, tracing back centuries through tradition. Astro Dozi bridges this cultural heritage with AI-powered computer vision. Scans the symbols in your cup and transforms them into a personal interpretation based on your birth chart.',
    history: 'Coffee ground reading has deep roots in Ottoman palace tradition. With coffee\'s arrival in Anatolia in the 16th century, reading grounds became part of daily life. Symbol families - birds, roads, letters, hearts - passed through generations. Today it remains one of Turkey\'s most beloved fortune practices.',
    howTo: [
      'Before drinking Turkish coffee, clarify your intention and think of loved ones',
      'After finishing, cover the cup and flip it upside down',
      'Wait 5-10 minutes for grounds to settle',
      'Photograph the cup\'s interior from 4 different angles',
      'AI identifies each symbol and interprets it by your sign and wish',
    ],
    method: 'Astro Dozi\'s coffee reading uses Google Gemini\'s multimodal vision model. Analyzing 4 cup photos, it recognizes specific symbols in grounds (birds, letters, line patterns, clusters) and matches them with Turkish traditional symbol dictionary. Results personalize by birth chart and zodiac sign. Nowhere else on App Store: no astrology app interprets a real physical object (coffee cup) via computer vision.',
    symbols: [
      { name: 'Bird', meaning: 'Good news, blessing, unexpected joy' },
      { name: 'Road', meaning: 'New beginning, travel, career change' },
      { name: 'Heart', meaning: 'Love, romantic development, relationship deepening' },
      { name: 'Money', meaning: 'Expected or sudden income, financial opportunity' },
      { name: 'Ring', meaning: 'Marriage, engagement, lasting commitment' },
      { name: 'Fish', meaning: 'Abundance, prosperity, gain beyond expectation' },
    ],
    cta: 'Photograph your cup, let Astro Dozi\'s AI read your grounds in seconds.',
  },
  {
    slug: 'tarot-reading',
    name: 'Tarot Reading',
    symbol: '🃏',
    sceneKind: 'tarot',
    accent: '#7C3AED',
    searchKeyword: 'tarot reading, tarot cards, online tarot, free tarot, tarot card reading, tarot card meanings',
    feature: 'tarot',
    tagline: 'Three Cards, One Intention, Infinite Meaning',
    intro: 'Tarot reading is an intuitive practice where cards drawn from a 78-card deck offer insight into past, present, and future through symbolism. Astro Dozi merges the classic Rider-Waite-Smith deck with AI interpretation power; each draw gains personal meaning.',
    history: 'Tarot began in 15th-century Italy as a card game, becoming mystical practice in the 18th century. Today it ranks among the world\'s most widespread divination systems. The 22 Major Arcana represent life\'s core archetypes (Fool, Magician, Empress, Lovers); 56 Minor Arcana reflect daily life details.',
    howTo: [
      'Clarify your intention: love, career, general guidance',
      'Ask your question aloud, open your heart',
      'Shuffle the deck intuitively and draw three cards',
      'Choose a spread: Past - Present - Future or Celtic Cross',
      'AI combines card symbolism with your birth chart for interpretation',
    ],
    method: 'Astro Dozi offers the full 78-card RWS deck. Single card, 3-card (past-present-future), or Celtic Cross spreads are possible. For each card, Gemini AI merges the card\'s meaning with your zodiac sign, birth chart, and question context. Unlike static tarot apps, the same card produces different readings on different days.',
    symbols: [
      { name: 'Fool (0)', meaning: 'New beginning, bold step, limitless potential' },
      { name: 'Lovers (VI)', meaning: 'Romantic love, choice, step toward partnership' },
      { name: 'Wheel (X)', meaning: 'Cycles change, fortune, fate\'s turn' },
      { name: 'Star (XVII)', meaning: 'Hope, renewal, spiritual guidance' },
      { name: 'Moon (XVIII)', meaning: 'Illusion, intuition, mysterious insights' },
      { name: 'World (XXI)', meaning: 'Completion, success, cycle\'s end' },
    ],
    cta: 'Set an intention and draw three cards; let AI read your tarot.',
  },
  {
    slug: 'dream-interpretation',
    name: 'Dream Interpretation',
    symbol: '💤',
    sceneKind: 'dream',
    accent: '#4F8DFD',
    searchKeyword: 'dream interpretation, dream meaning, dream analysis, what dreams mean, free dream analysis',
    feature: 'dream',
    tagline: 'The Language of Symbols, Decoded',
    intro: 'Dream interpretation is the art of decoding subconscious messages in symbols seen during sleep. Astro Dozi analyzes your dream, catalogs its symbols, reads emotional undercurrents, and reveals possible meaning in your waking life.',
    history: 'Dream interpretation spans both religious and psychological traditions. Starting with ancient Egypt\'s Chester Beatty III "Dream Book," developing through Ibn Sirin\'s Islamic interpretations, entering modern psychology with Freud and Jung - this practice seeks the root meaning of symbols in the subconscious.',
    howTo: [
      'Upon waking, jot down your dream; details fade fast',
      'Write dream\'s core elements: who, what, where, feeling',
      'Select the dominant emotion (happy, scared, strange)',
      'Let AI extract symbols and blend them with your context',
      'Compare suggested meaning to real-life situations',
    ],
    method: 'Astro Dozi\'s dream interpretation uses Gemini AI to analyze dream text symbols at the intersection of Ibn Sirin tradition, Jung archetypes, and modern psychology. Keep a dream journal - AI analyzes weekly patterns: which symbols repeat, what emotions dominate, what themes remain unprocessed.',
    symbols: [
      { name: 'Water', meaning: 'Emotional state, subconscious, cleansing or drowning' },
      { name: 'Flying', meaning: 'Desire for freedom, loss of control, opening to dreams' },
      { name: 'Losing Teeth', meaning: 'Transformation anxiety, loss of control, life transition' },
      { name: 'Snake', meaning: 'Transformation, threat, healing power, hidden knowledge' },
      { name: 'House', meaning: 'Your self, spiritual space, state of your identity' },
      { name: 'Baby', meaning: 'New project, beginning, a quality needing protection' },
    ],
    cta: 'Write tonight\'s dream, let AI prepare your weekly analysis.',
  },
  {
    slug: 'palm-reading',
    name: 'Palm Reading',
    symbol: '✋',
    sceneKind: 'palm',
    accent: '#EC4899',
    searchKeyword: 'palm reading, hand reading, palmistry, online palm reading, hand lines fortune telling',
    feature: 'palm',
    tagline: 'Your Life Story, Traced in Lines',
    intro: 'Palm reading (hand reading, palmistry) is the art of extracting insight about personality and life from the shape and length of lines in your hand. Astro Dozi brings digital depth to this ancient art through AI vision analyzing your hand\'s photo.',
    history: 'Palm reading traces back 4,000 years to India\'s Vedic tradition. Studied by Aristotle in ancient Greece, merged with traditional medicine in China. In the West, 19th-century science called it "chiromancy." Three main lines (heart, life, head) and the active hand (your writing hand) hold central importance.',
    howTo: [
      'Choose your active hand (usually your writing hand)',
      'Face your palm in well-lit space',
      'Gently stretch your hand so lines are clear',
      'Photograph your palm with all lines fully visible',
      'Let AI separately interpret heart - life - head - fate lines',
    ],
    method: 'Astro Dozi\'s palm analysis uses Gemini\'s vision model to detect main lines (heart, life, head, fate) from your hand photo. Each line\'s length, depth, and starting point match traditional chiromancy data. Result personalizes by birth chart. Like ground reading, this is computer vision-based - nowhere else on App Store.',
    symbols: [
      { name: 'Life Line', meaning: 'Life energy, health, major life changes' },
      { name: 'Heart Line', meaning: 'Romantic relationships, emotional depth, love life' },
      { name: 'Head Line', meaning: 'Mental ability, decision style, thinking structure' },
      { name: 'Fate Line', meaning: 'Career, success, external influence' },
      { name: 'Sun Line', meaning: 'Artistic talent, recognition, path to success' },
      { name: 'Marriage Line', meaning: 'Significant relationships, marriage or deep bonds' },
    ],
    cta: 'Photograph your palm, let AI analyze your lines.',
  },
];
