// 4 fal turu icin SEO landing icerik datasi (Turkce karakterli, premium copy).

export const fortunes = [
  {
    slug: 'kahve-fali',
    name: 'Kahve Falı',
    symbol: '☕',
    sceneKind: 'coffee',
    accent: '#C97A40',
    searchKeyword: 'kahve falı, kahve falı bak, online kahve falı, kahve telvesi yorumu, ücretsiz kahve falı',
    feature: 'coffee',
    tagline: 'Telvenden Yorum, Yapay Zekadan İçgörü',
    intro: 'Kahve falı, Türk kahvesinin ardından fincanın telvesinde oluşan şekillerin yorumlanmasıyla yapılan, yüzyıllara uzanan geleneksel bir fal türüdür. Astro Dozi, bu kültürel mirası yapay zeka destekli bilgisayar görüşü ile buluşturur. Fincanındaki sembolleri tarar, doğum haritana göre kişisel bir yoruma dönüştürür.',
    history: 'Kahve falının Osmanlı sarayına uzanan köklü bir geçmişi vardır. 16. yüzyılda kahvenin Anadolu\'ya gelmesiyle birlikte, telve okuma sanatı da gündelik yaşamın bir parçası olmuştur. Kuş, yol, harf, kalp gibi sembol ailesi kuşaktan kuşağa aktarıldı. Bugün hâlâ Türkiye\'de en sevilen fal türlerinden biridir.',
    howTo: [
      'Türk kahveni içmeden önce niyetini netleştir, sevdiklerini düşün',
      'Kahveyi bitirdikten sonra fincanın ağzını kapatıp ters çevir',
      'Telvenin oturması için 5-10 dakika bekle',
      'Fincanın içinden 4 farklı açıdan fotoğraf çek',
      'Yapay zeka her sembolü tanır, dileğine ve burcuna göre yorumlar',
    ],
    method: 'Astro Dozi\'nin kahve falı, Google Gemini\'nin çoklu modaliteli görüş modelini kullanır. 4 fincan fotoğrafını analiz ederken telvedeki spesifik sembolleri (kuş, harf, yol benzeri çizgiler, kümeler) tanır ve geleneksel Türk sembol sözlüğüyle eşleştirir. Sonuç doğum haritana ve burcuna göre kişiselleştirilir. App Store\'da bir başka eşi yok: hiçbir astroloji uygulaması gerçek bir nesneyi (kahve fincanı) bilgisayar görüşü ile yorumlamıyor.',
    symbols: [
      { name: 'Kuş', meaning: 'İyi haber, müjde, beklenmedik bir sevinç' },
      { name: 'Yol', meaning: 'Yeni başlangıç, seyahat, kariyer değişikliği' },
      { name: 'Kalp', meaning: 'Aşk, romantik bir gelişme, ilişki derinleşmesi' },
      { name: 'Para', meaning: 'Beklenen veya ani gelir, finansal fırsat' },
      { name: 'Yüzük', meaning: 'Evlilik, söz, kalıcı bir bağlılık' },
      { name: 'Balık', meaning: 'Bolluk, bereket, beklenenden çok kazanç' },
    ],
    cta: 'Fincanın fotoğrafını çek, Astro Dozi\'nin AI yorumcusu birkaç saniyede telveni okusun.',
  },
  {
    slug: 'tarot-fali',
    name: 'Tarot Falı',
    symbol: '🃏',
    sceneKind: 'tarot',
    accent: '#7C3AED',
    searchKeyword: 'tarot falı, tarot kart falı, online tarot, ücretsiz tarot, tarot okuması, tarot kart anlamları',
    feature: 'tarot',
    tagline: 'Üç Kart, Bir Niyet, Sonsuz Yorum',
    intro: 'Tarot falı, 78 kartlık bir desteden çekilen kartların sembolizmi aracılığıyla geçmiş, şimdiki an ve gelecek hakkında içgörü sunan bir sezgi pratiğidir. Astro Dozi, klasik Rider-Waite-Smith destesini AI yorumlama gücüyle birleştirir; her çekime kişisel anlam katar.',
    history: 'Tarot, 15. yüzyılda İtalya\'da iskambil oyunu olarak başlayıp, 18. yüzyılda mistik amaçla kullanılmaya başlandı. Bugün dünyanın en yaygın fal sistemlerinden biridir. 22 Büyük Arkana karti hayatın temel arketiplerini (Deli, Büyücü, İmparatoriçe, Aşık); 56 Küçük Arkana ise gündelik yaşamın detaylarını temsil eder.',
    howTo: [
      'Niyetini netleştir: aşk, kariyer, genel rehberlik',
      'Aklındaki soruyu sor, kalbini aç',
      'Desteyi sezginle karıştır ve üç kart seç',
      'Geçmiş - şimdi - gelecek ya da Celtic Cross gibi açılım seç',
      'AI, kartın sembolizmini doğum haritanla birleştirerek yorum yazar',
    ],
    method: 'Astro Dozi tam 78 kartlık RWS destesi sunar. Tek kart, 3-kart (geçmiş-şimdi-gelecek) veya Celtic Cross açılımları yapılabilir. Her kart için Gemini AI, kartın anlamını senin burcun, doğum haritan ve sorunun bağlamıyla birleştirir. Statik tarot uygulamalarının aksine, aynı kart farklı bir gün için farklı yorum üretir.',
    symbols: [
      { name: 'Deli (0)', meaning: 'Yeni bir başlangıç, cesur adım, sınırsız potansiyel' },
      { name: 'Aşık (VI)', meaning: 'Aşk ilişkisi, seçim, hayat ortaklığına adım' },
      { name: 'Çark (X)', meaning: 'Döngülerin değişimi, şans, kader dönüşü' },
      { name: 'Yıldız (XVII)', meaning: 'Umut, yenilenme, ruhsal rehberlik' },
      { name: 'Ay (XVIII)', meaning: 'İllüzyon, sezgi, gizemli içgörüler' },
      { name: 'Dünya (XXI)', meaning: 'Tamamlanma, başarı, döngünün sonu' },
    ],
    cta: 'Bir niyet edip üç kart çek; AI senin tarotunu okusun.',
  },
  {
    slug: 'ruya-yorumu',
    name: 'Rüya Yorumu',
    symbol: '💤',
    sceneKind: 'dream',
    accent: '#4F8DFD',
    searchKeyword: 'rüya yorumu, rüya tabiri, rüyada görmek, rüya tabirleri online, rüya analizi ücretsiz',
    feature: 'dream',
    tagline: 'Sembollerin Diliyle Bilinçaltı',
    intro: 'Rüya yorumu, gece gördüğün sembollerin bilinçaltı mesajlarını çözme sanatıdır. Astro Dozi, anlattığın rüyayı analiz eder, sembolleri sözlükleştirir, duygusal arka planı okur ve hayatındaki olası karşılığını sunar.',
    history: 'Rüya yorumu hem dini hem psikolojik bir gelenektir. Antik Mısır\'da Chester Beatty III "Rüya Kitabı" ile başlayan, İbn Sirin\'in İslami yorumlarında gelişen, Freud ve Jung\'la modern psikolojiye giren bu pratik, sembolün bilinçaltındaki kök anlamını bulmayı hedefler.',
    howTo: [
      'Uyanır uyanmaz rüyanın notunu al; detay çabucak silinir',
      'Rüyanın temel öğelerini yaz: kim, ne, nerede, his',
      'Rüyandaki dominant duyguyu (mutlu, korkulu, tuhaf) seç',
      'AI sembolleri ayıklayıp kişisel bağlamla birleştirsin',
      'Önerilen anlam ile gerçek hayatındaki durumu karşılaştır',
    ],
    method: 'Astro Dozi\'nin rüya tabiri, Gemini AI ile rüya metnindeki sembolleri İbn Sirin geleneği, Jung arketipleri ve modern psikolojinin kesişiminde yorumlar. Rüya günlüğü tutarsan AI haftalık desenleri analiz eder: hangi semboller tekrar ediyor, hangi duygu hâkim, hangi konu işlenmemiş bir endişe.',
    symbols: [
      { name: 'Su', meaning: 'Duygusal durum, bilinçaltı, arınma ya da boğulma' },
      { name: 'Uçmak', meaning: 'Özgürlük arzusu, kontrol kaybı, hayallere açılım' },
      { name: 'Diş Dökülmesi', meaning: 'Dönüşüm kaygısı, kontrol kaybı, yeni evreye geçiş' },
      { name: 'Yılan', meaning: 'Dönüşüm, tehdit, şifa gücü, gizli bilgi' },
      { name: 'Ev', meaning: 'Kendi benliğin, ruhsal alanın, kimliğinin durumu' },
      { name: 'Bebek', meaning: 'Yeni proje, başlangıç, korunması gereken bir nitelik' },
    ],
    cta: 'Bu gece gördüğün rüyayı yaz, AI haftalık analizini hazırlasın.',
  },
  {
    slug: 'avuc-ici-fali',
    name: 'Avuç İçi Falı',
    symbol: '✋',
    sceneKind: 'palm',
    accent: '#EC4899',
    searchKeyword: 'avuç içi falı, el falı, palmistry, online el falı, el çizgilerinden fal',
    feature: 'palm',
    tagline: 'Çizgilerinden Hayat Hikayen',
    intro: 'Avuç içi falı (el falı, palmistry), elindeki çizgilerin biçim ve uzunluklarından kişilik ve yaşamla ilgili içgörü çıkarma sanatıdır. Astro Dozi, elinin fotoğrafını analiz eden AI görüşü ile bu eski sanata dijital bir derinlik katar.',
    history: 'El falı, 4000 yıl öncesine Hindistan\'a uzanan Veda geleneğiyle başlar. Antik Yunan\'da Aristoteles tarafından incelendi, Çin\'de geleneksel tıpla birleşti. Batı\'da 19. yüzyılda "chiromancy" adıyla bilim olarak da değerlendirildi. Üç ana çizgi (kalp, hayat, kafa) ve aktif el (yazı yazdığın) merkezi öneme sahiptir.',
    howTo: [
      'Aktif elini (genelde yazı yazdığın el) seç',
      'Avuç içini iyi aydınlatılmış bir alana çevir',
      'Çizgilerin net görünmesi için elini hafifçe ger',
      'Avucunun fotoğrafını tüm çizgiler görünecek şekilde çek',
      'AI kalp - hayat - kafa - kader çizgilerini ayrı ayrı yorumlasın',
    ],
    method: 'Astro Dozi\'nin avuç içi analizi, Gemini\'nin görüş modeliyle elinin fotoğrafındaki ana çizgileri (kalp, hayat, kafa, kader) tespit eder. Her çizginin uzunluğu, derinliği ve başlangıç noktası geleneksel chiromancy verisiyle eşleştirilir. Sonuç doğum haritana göre kişiselleştirilir. Telve okuma gibi, bu da App Store\'da olmayan bilgisayar görüşü tabanlı bir özelliktir.',
    symbols: [
      { name: 'Hayat Çizgisi', meaning: 'Yaşam enerjisi, sağlık, hayatındaki büyük değişimler' },
      { name: 'Kalp Çizgisi', meaning: 'Romantik ilişkiler, duygusal derinlik, aşk hayatı' },
      { name: 'Kafa Çizgisi', meaning: 'Zihinsel yetenek, karar verme tarzı, düşünce yapısı' },
      { name: 'Kader Çizgisi', meaning: 'Kariyer, başarı, dış dünyanın etkisi' },
      { name: 'Güneş Çizgisi', meaning: 'Sanatsal yetenek, tanınma, başarıya giden yol' },
      { name: 'Evlilik Çizgisi', meaning: 'Önemli ilişkiler, evlilik veya derin bağlar' },
    ],
    cta: 'Avuç içinin fotoğrafını çek, AI çizgilerini analiz etsin.',
  },
];
