// 12 burc icin SEO landing icerik datasi.
// generate-zodiac-pages.mjs bu dosyayi okuyup HTML uretir.

export const zodiacs = [
  {
    slug: 'koc',
    name: 'Koc',
    nameAccented: 'Koç',
    symbol: '♈',
    dateRange: '21 Mart - 19 Nisan',
    element: 'Ateş',
    ruler: 'Mars',
    quality: 'Öncü',
    appSign: 'aries',
    intro: 'Koç burcu, zodyakın ilk burcudur ve Ateş elementinin öncüsüdür. Mars yönetiminde hızlı, cesur ve liderlik vasfı güçlü bir karakter sergiler. Yeni başlangıçların, girişimciliğin ve doğal cesaretin simgesidir.',
    characteristics: [
      'Liderlik ruhu güçlü, ilk adımı atan kişidir',
      'Cesur, dolaysız ve risk almaktan çekinmez',
      'Sabırsız olabilir, hızlı sonuç ister',
      'Mantık yerine sezgiye güvenir, anında karar verir',
      'Rekabeti sever, kazanmak motive eder',
    ],
    love: 'Koç aşkta da öncüdür. İlk adımı atmaktan korkmaz, doğrudan flort eder. İlişkide tutku ve aksiyon arar, rutin onu sıkar. Sadık bir partner olur ama monoton ilişkide solar. En iyi eşleşme: Yay, Aslan, İkizler.',
    career: 'Yöneticilik, girişimcilik, sporculuk, askeri/güvenlik alanları ve acil müdahale gerektiren mesleklerde parlar. Patron olmak ister; baskaldiri ve emir alamama eğilimi güçlüdür. Hız gerektiren rollerde verim alır.',
    bestMatch: ['Aslan', 'Yay', 'İkizler', 'Kova'],
    worstMatch: ['Yengeç', 'Oğlak'],
    celebrities: ['Lady Gaga', 'Robert Downey Jr.', 'Mariah Carey', 'Emma Watson', 'Kourtney Kardashian'],
    luckyNumber: '9',
    luckyColor: 'Kırmızı',
    luckyDay: 'Salı',
    luckyStone: 'Elmas',
  },
  {
    slug: 'boga',
    name: 'Boga',
    nameAccented: 'Boğa',
    symbol: '♉',
    dateRange: '20 Nisan - 20 Mayıs',
    element: 'Toprak',
    ruler: 'Venüs',
    quality: 'Sabit',
    appSign: 'taurus',
    intro: 'Boğa burcu, zodyakın Toprak elementli sabit burcudur ve Venüs yönetimindedir. Sadık, sabırlı ve dayanıklıdır. Maddi güvenliği, güzel şeyleri ve duygusal istikrarı önemser.',
    characteristics: [
      'Son derece sadık ve güvenilirdir',
      'Sabırlı, kararlı, hedefine yavas ama emin ulasir',
      'Değişime dirençlidir, rutinden mutludur',
      'Duyusal zevkleri sever: yemek, sanat, dokunmatik konfor',
      'Kıskanç olabilir, sahiplenmeyi aşırı yapar',
    ],
    love: 'Boğa aşkta uzun vadeli ve güvenli ilişki arar. Sadık bir partnerdir, evlilik ve aile yönelimi güçlüdür. Dokunsal sevgi diliyle konuşur, somut hediyeler ve fiziksel yakınlık değerlidir.',
    career: 'Finans, bankacılık, gayrimenkul, gastronomi, tarım, sanat ve müzik alanları Boğa\'ya uygundur. İstikrarlı ve birikim odaklı işlerde başarı yakalar. Para yönetimi doğal yetenektir.',
    bestMatch: ['Başak', 'Oğlak', 'Yengeç', 'Balık'],
    worstMatch: ['Aslan', 'Akrep'],
    celebrities: ['Adele', 'David Beckham', 'Cher', 'George Clooney', 'Penelope Cruz'],
    luckyNumber: '6',
    luckyColor: 'Yeşil',
    luckyDay: 'Cuma',
    luckyStone: 'Zümrüt',
  },
  {
    slug: 'ikizler',
    name: 'Ikizler',
    nameAccented: 'İkizler',
    symbol: '♊',
    dateRange: '21 Mayıs - 20 Haziran',
    element: 'Hava',
    ruler: 'Merkür',
    quality: 'Değişken',
    appSign: 'gemini',
    intro: 'İkizler burcu, Hava elementinin değişken burcudur ve Merkür yönetimindedir. İletişim, merak ve zihinsel çeviklik onun kişiliğinin özüdür. İki kutuplu, çok yönlü ve sosyal bir burc.',
    characteristics: [
      'Konuşkan, meraklı, hızlı ��ğrenir',
      'Sosyal kelebek, geniş arkadaş çevresi',
      'Çift yönlü karakter: tutarlılık zayıf olabilir',
      'Espri yeteneği güçlü, hayatı hafif yaşar',
      'Sıkılganlık eşiği düşük, sürekli yeni şey ister',
    ],
    love: 'İkizler aşkta zihinsel çekim arar. Konuşabilen, ona meydan okuyan partner ister. Tek eşli olmak zor olabilir, çeşitlilik ihtiyacı yüksektir. Mizah ve dil oyunu ilişkide kritik.',
    career: 'Gazetecilik, yazılım, satış, halkla ilişkiler, eğitim, çeviri ve sosyal medya alanları İkizler\'e özel uygundur. Birden fazla işi paralel yürütebilir.',
    bestMatch: ['Terazi', 'Kova', 'Koç', 'Aslan'],
    worstMatch: ['Balık', 'Başak'],
    celebrities: ['Marilyn Monroe', 'Angelina Jolie', 'Kanye West', 'Johnny Depp', 'Nicole Kidman'],
    luckyNumber: '5',
    luckyColor: 'Sarı',
    luckyDay: 'Çarşamba',
    luckyStone: 'Akik',
  },
  {
    slug: 'yengec',
    name: 'Yengec',
    nameAccented: 'Yengeç',
    symbol: '♋',
    dateRange: '21 Haziran - 22 Temmuz',
    element: 'Su',
    ruler: 'Ay',
    quality: 'Öncü',
    appSign: 'cancer',
    intro: 'Yengeç, Su elementinin öncü burcudur ve Ay yönetimindedir. Duygusal derinliği, koruyucu içgüdüsü ve aile bağlılığı ile bilinir. Hassas, sezgisel ve empati yüksektir.',
    characteristics: [
      'Duygusal zekası çok yüksek, empati doğal',
      'Aile ve ev hayatı merkezde, koruyucu',
      'Sezgileri kuvvetli, ruh halini hızlı okur',
      'Alıngan, kırılgan; kabuğuna çekilebilir',
      'Sadık ve sevdiğini fedakarca koruyan',
    ],
    love: 'Yengeç aşkta derin, kalıcı bağ arar. Aile kurmaya yatkındır, ilişkide güvenliği her şeyin üstünde tutar. Partnerini hem korur hem korunmak ister. Romantizm yoğundur.',
    career: 'Sağlık, psikoloji, eğitim, sosyal hizmet, gastronomi, dekorasyon, tarih araştırmacılığı. Başkalarına bakım vermek ona iyi gelir.',
    bestMatch: ['Akrep', 'Balık', 'Boğa', 'Başak'],
    worstMatch: ['Koç', 'Terazi'],
    celebrities: ['Tom Hanks', 'Selena Gomez', 'Ariana Grande', 'Tom Cruise', 'Lana Del Rey'],
    luckyNumber: '2',
    luckyColor: 'Beyaz',
    luckyDay: 'Pazartesi',
    luckyStone: 'İnci',
  },
  {
    slug: 'aslan',
    name: 'Aslan',
    nameAccented: 'Aslan',
    symbol: '♌',
    dateRange: '23 Temmuz - 22 Ağustos',
    element: 'Ateş',
    ruler: 'Güneş',
    quality: 'Sabit',
    appSign: 'leo',
    intro: 'Aslan, Ateş elementinin sabit burcudur ve Güneş yönetimindedir. Güven, sahne, dramatik karizma ve cesaretin temsilcisidir. Doğası itibariyle dikkat çeker.',
    characteristics: [
      'Öz güveni yüksek, doğal lider',
      'Cömert, sadık, dramatik karizma sahibi',
      'Beğenilmeyi sever, sahnede parıldar',
      'Gururludur, kırılganlığını sergilemekten kaçınır',
      'Yaratıcı, neşeli, hayat dolu',
    ],
    love: 'Aslan aşkta sahnenin merkezi olur. Tutku, dramatik aşk hikayeleri ve takdir arar. Partnerin onu görmesi şarttir. Sadık bir eştir ama ihaneti affetmez.',
    career: 'Yöneticilik, oyunculuk, müzik, kamera önü, etkinlik organizasyonu, çocuk eğitimi. Sahne onun çalışma alanı; dikkat çeken her işte parıldar.',
    bestMatch: ['Koç', 'Yay', 'İkizler', 'Terazi'],
    worstMatch: ['Boğa', 'Akrep'],
    celebrities: ['Madonna', 'Barack Obama', 'Jennifer Lopez', 'Mick Jagger', 'Sandra Bullock'],
    luckyNumber: '1',
    luckyColor: 'Altın',
    luckyDay: 'Pazar',
    luckyStone: 'Yakut',
  },
  {
    slug: 'basak',
    name: 'Basak',
    nameAccented: 'Başak',
    symbol: '♍',
    dateRange: '23 Ağustos - 22 Eylül',
    element: 'Toprak',
    ruler: 'Merkür',
    quality: 'Değişken',
    appSign: 'virgo',
    intro: 'Başak, Toprak elementinin değişken burcudur ve Merkür yönetimindedir. Mükemmeliyetçilik, analitik düşünce, hizmet ve detaycılık onun çekirdek nitelikleridir.',
    characteristics: [
      'Analitik zekası çok yüksek, detaycı',
      'Mükemmeliyetçi, en iyiyi ister',
      'Yardımsever, başkalarına hizmet etmekten zevk alır',
      'Eleştirel olabilir, kendini ve etrafını sorgular',
      'Pratik, organize, planlamada usta',
    ],
    love: 'Başak aşkta şefkat ve istikrar arar. Romantizmden çok gerçek hayat partnerliği önemlidir. Sevgisini hizmetle gösterir. Kırılgandır, eleştiri kabul ettiremez.',
    career: 'Sağlık, araştırma, muhasebe, yazılım, editörlük, kalite kontrol, beslenme. Detay gerektiren her işte parıldar.',
    bestMatch: ['Boğa', 'Oğlak', 'Yengeç', 'Akrep'],
    worstMatch: ['İkizler', 'Yay'],
    celebrities: ['Beyoncé', 'Keanu Reeves', 'Michael Jackson', 'Cameron Diaz', 'Zendaya'],
    luckyNumber: '5',
    luckyColor: 'Lacivert',
    luckyDay: 'Çarşamba',
    luckyStone: 'Safir',
  },
  {
    slug: 'terazi',
    name: 'Terazi',
    nameAccented: 'Terazi',
    symbol: '♎',
    dateRange: '23 Eylül - 22 Ekim',
    element: 'Hava',
    ruler: 'Venüs',
    quality: 'Öncü',
    appSign: 'libra',
    intro: 'Terazi, Hava elementinin öncü burcudur ve Venüs yönetimindedir. Denge, adalet, estetik ve ilişki kurma yeteneği onun temel özellikleridir.',
    characteristics: [
      'Adaletli, dengeli, diplomatik',
      'Estetik duygusu çok gelişmiş',
      'Karar vermekte zorlanır, her iki tarafı dinler',
      'İlişki odaklı, yalnız hissetmek istemez',
      'Sevimli, sosyal, tartışmadan kaçınan',
    ],
    love: 'Terazi aşkta partnerini idealize eder. Romantizm, jest, kibarlık onun dilidir. Yalnız kalmaktan kaçınır; ilişki onun doğal halidir.',
    career: 'Hukuk, diplomasi, mimari, moda, iç mimari, danışmanlık, sanat. İnsanlarla çalışmayı gerektiren her işte iyi.',
    bestMatch: ['İkizler', 'Kova', 'Aslan', 'Yay'],
    worstMatch: ['Yengeç', 'Oğlak'],
    celebrities: ['Kim Kardashian', 'Will Smith', 'Bruno Mars', 'Gwyneth Paltrow', 'Cardi B'],
    luckyNumber: '7',
    luckyColor: 'Pembe',
    luckyDay: 'Cuma',
    luckyStone: 'Opal',
  },
  {
    slug: 'akrep',
    name: 'Akrep',
    nameAccented: 'Akrep',
    symbol: '♏',
    dateRange: '23 Ekim - 21 Kasım',
    element: 'Su',
    ruler: 'Pluton',
    quality: 'Sabit',
    appSign: 'scorpio',
    intro: 'Akrep, Su elementinin sabit burcudur ve Pluton yönetimindedir. Yoğun duyguları, sezgisel derinliği ve dönüştürücü gücüyle bilinir.',
    characteristics: [
      'Tutkulu, derin, gizemli',
      'Sezgileri çok kuvvetli, manipulasyonu hisseder',
      'İntikamcı olabilir, hatayı unutmaz',
      'Dönüşmeye ve dönüştürmeye yatkın',
      'Sadık, mahremiyet değeri yüksek',
    ],
    love: 'Akrep aşkta tam teslimiyet arar. Yüzeysel ilişki onu tatmin etmez. Kıskançtır ama sadık bir partnerdir. İhanet onu derin yaralar.',
    career: 'Psikoloji, araştırmacılık, tıp (cerrahi), polisiye, sigorta, finans, gizli servis. Derinlik gerektiren her işte başarılı.',
    bestMatch: ['Yengeç', 'Balık', 'Başak', 'Oğlak'],
    worstMatch: ['Aslan', 'Kova'],
    celebrities: ['Drake', 'Leonardo DiCaprio', 'Bill Gates', 'Julia Roberts', 'Katy Perry'],
    luckyNumber: '8',
    luckyColor: 'Bordo',
    luckyDay: 'Salı',
    luckyStone: 'Topaz',
  },
  {
    slug: 'yay',
    name: 'Yay',
    nameAccented: 'Yay',
    symbol: '♐',
    dateRange: '22 Kasım - 21 Aralık',
    element: 'Ateş',
    ruler: 'Jüpiter',
    quality: 'Değişken',
    appSign: 'sagittarius',
    intro: 'Yay, Ateş elementinin değişken burcudur ve Jüpiter yönetimindedir. Özgürlük, macera, felsefe ve uzun mesafelerin burcudur.',
    characteristics: [
      'Özgürlük aşığı, seyahat ve macera tutkunu',
      'Filozof ruh, büyük resmi görür',
      'Açık sözlü, bazen patavatsız',
      'Optimist, neşeli, espriydir',
      'Sıkılganlık eşiği düşük, bağlılık zor',
    ],
    love: 'Yay aşkta özgürlük şart. Maceracı, beraber kesfedebilen partner ister. Tek eşlilik zor ama doğru kişiyle gerçekleşir. Mizah şart.',
    career: 'Seyahat, akademi, hukuk, yayıncılık, spor, eğitim, dini ve felsefi alanlar. Özgür çalışma koşulları şart.',
    bestMatch: ['Koç', 'Aslan', 'Kova', 'Terazi'],
    worstMatch: ['Başak', 'Balık'],
    celebrities: ['Britney Spears', 'Taylor Swift', 'Brad Pitt', 'Steven Spielberg', 'Tina Turner'],
    luckyNumber: '3',
    luckyColor: 'Mor',
    luckyDay: 'Perşembe',
    luckyStone: 'Türkuaz',
  },
  {
    slug: 'oglak',
    name: 'Oglak',
    nameAccented: 'Oğlak',
    symbol: '♑',
    dateRange: '22 Aralık - 19 Ocak',
    element: 'Toprak',
    ruler: 'Satürn',
    quality: 'Öncü',
    appSign: 'capricorn',
    intro: 'Oğlak, Toprak elementinin öncü burcudur ve Satürn yönetimindedir. Hedef odaklı, disiplinli, sorumluluk sahibi ve uzun vadeli düşünen bir karakter sergiler.',
    characteristics: [
      'Disiplinli, sorumluluk sahibi, sabırlı',
      'Uzun vadeli planlayıcı, hedefe yavaş ama emin yaklaşır',
      'Ciddi, oturaklı, mizahı kuru olabilir',
      'Materyalist eğilim, statu güvenliği önemli',
      'Sadık, güvenilir, geleneksel değerleri benimseyen',
    ],
    love: 'Oğlak aşkta uzun vadeli ve ciddi ilişki arar. Yavaş açılır ama bir kez bağlandı mı sadıktır. Partnerine maddi ve duygusal güvence sunar.',
    career: 'Yöneticilik, finans, hukuk, müh��ndislik, müteahhitlik, devlet görevleri. Hiyerarşik yapılarda zirveye çıkar.',
    bestMatch: ['Boğa', 'Başak', 'Akrep', 'Balık'],
    worstMatch: ['Koç', 'Terazi'],
    celebrities: ['Michelle Obama', 'Denzel Washington', 'Jim Carrey', 'Kate Middleton', 'Bradley Cooper'],
    luckyNumber: '4',
    luckyColor: 'Koyu Gri',
    luckyDay: 'Cumartesi',
    luckyStone: 'Oniks',
  },
  {
    slug: 'kova',
    name: 'Kova',
    nameAccented: 'Kova',
    symbol: '♒',
    dateRange: '20 Ocak - 18 Şubat',
    element: 'Hava',
    ruler: 'Uranüs',
    quality: 'Sabit',
    appSign: 'aquarius',
    intro: 'Kova, Hava elementinin sabit burcudur ve Uranüs yönetimindedir. Özgün düşünce, insan hakları, teknoloji ve devrimciliği temsil eder.',
    characteristics: [
      'Özgün, bağımsız, kalibalardan farklı düşünür',
      'Hayalperest ama mantık odaklı',
      'Topluluk için çalışmaya yatkın, idealist',
      'Duygusal mesafeli olabilir, soyut sever',
      'Teknolojiyle arı karışık, gelecekci',
    ],
    love: 'Kova aşkta zihinsel çekim ve özgürlük arar. Geleneksel ilişki kalıpları onu sıkar. Arkadaşlık temelli ilişki idealdir. Yoğun duygusallık zorlayıcı olabilir.',
    career: 'Teknoloji, mühendislik, araştırmacılık, sivil toplum, astronomi, modern sanat, sosyal yenilik. İnsan iyiliğine yönelik işlerde parıldar.',
    bestMatch: ['İkizler', 'Terazi', 'Koç', 'Yay'],
    worstMatch: ['Boğa', 'Akrep'],
    celebrities: ['Oprah Winfrey', 'Shakira', 'Harry Styles', 'Jennifer Aniston', 'Ed Sheeran'],
    luckyNumber: '11',
    luckyColor: 'Elektrik Mavisi',
    luckyDay: 'Cumartesi',
    luckyStone: 'Ametist',
  },
  {
    slug: 'balik',
    name: 'Balik',
    nameAccented: 'Balık',
    symbol: '♓',
    dateRange: '19 Şubat - 20 Mart',
    element: 'Su',
    ruler: 'Neptün',
    quality: 'Değişken',
    appSign: 'pisces',
    intro: 'Balık, Su elementinin değişken burcudur ve Neptün yönetimindedir. Empati, hayal gücü, müzik ve ruhsal derinliğin temsilcisidir.',
    characteristics: [
      'Yüksek empati, başkalarının duygusunu emer',
      'Hayalperest, sanatsal yetenek yüksek',
      'Sezgiseldir, mistik ilgileri vardır',
      'Kaçış eğilimi, gerçeklikten uzaklaşabilir',
      'Şefkatli, kendinden önce başkasını düşünür',
    ],
    love: 'Balık aşkta ruh eşi arar. Romantik, fedakar, duygusal yoğun bir partnerdir. Bazen kendini kaybetme riski var, partnerinde çözülür.',
    career: 'Müzik, sinema, edebiyat, sağlık (özellikle terapi), fotoğraf, spiritualizm, dans. Yaratıcı ve duygusal alan onun doğası.',
    bestMatch: ['Yengeç', 'Akrep', 'Boğa', 'Oğlak'],
    worstMatch: ['İkizler', 'Yay'],
    celebrities: ['Rihanna', 'Justin Bieber', 'Albert Einstein', 'Steve Jobs', 'Elizabeth Taylor'],
    luckyNumber: '7',
    luckyColor: 'Deniz Yesili',
    luckyDay: 'Perşembe',
    luckyStone: 'Akuamarin',
  },
];
